### PR TITLE
Remove unnecessary try/catch block as to not lose the stack trace

### LINKED ISSUE #1809: [Bug]: Refit is losing the stacktrace due to throw ex in the client implementation
### Describe the bug 🐞

When using integration tests with WebApplicationFactory it is handy to be able to see the full stack trace. Unfortunately refit's code gen generates this:
```
try
            {
                return await ((global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>)______func(this.Client, ______arguments)).ConfigureAwait(false);
            }
            catch (global::System.Exception ______ex)
            {
                throw ______ex;
            }
```

This causes the entire stack trace of the exception to be discarded:
```
System.Exception : fooba
   at Refit.Implementation.Generated.CleanAspCoreApiTestsEndpointsDepartmentsIDepartmentApiClient.global::CleanAspCore.Api.Tests.Endpoints.Departments.IDepartmentApiClient.CreateDepartment(CreateDepartmentRequest createDepartmentRequest) in H:\git\CleanAspCoreWebApiTemplate\CleanAspCore.Api.Tests\obj\Debug\net8.0\InterfaceStubGeneratorV2\Refit.Generator.InterfaceStubGeneratorV2\IDepartmentApiClient.g.cs:line 96
   at CleanAspCore.Api.Tests.Endpoints.Departments.AddDepartmentsTests.CreateDepartment_IsAdded() in H:\git\CleanAspCoreWebApiTemplate\CleanAspCore.Api.Tests\Endpoints\Departments\AddDepartmentsTests.cs:line 15
```

When using the httpclient directly you get a much more detailed stacktrace:
```
System.Exception : fooba
   at CleanAspCore.Endpoints.Departments.AddDepartments.Handle(HrContext context, CreateDepartmentRequest createDepartmentRequest, CancellationToken cancellationToken) in H:\git\CleanAspCoreWebApiTemplate\CleanAspCore\Endpoints\Departments\AddDepartments.cs:line 38
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<TaskOfTToValueTaskOfObject>g__ExecuteAwaited|92_0[T](Task`1 task)
   at CleanAspCore.Common.GenericValidation.ValidationFilter`1.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next) in H:\git\CleanAspCoreWebApiTemplate\CleanAspCore\Common\GenericValidation\ValidationFilter.cs:line 16
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteValueTaskOfObject>g__ExecuteAwaited|129_0(ValueTask`1 valueTask, HttpContext httpContext, JsonTypeInfo`1 jsonTypeInfo)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.CookieContainerHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at CleanAspCore.Api.Tests.Endpoints.Departments.AddDepartmentsTests.CreateDepartment_IsAdded() in H:\git\CleanAspCoreWebApiTemplate\CleanAspCore.Api.Tests\Endpoints\Departments\AddDepartmentsTests.cs:line 14
```

If this code was generated the stack trace would be preserved:
```
try
            {
                return await ((global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>)______func(this.Client, ______arguments)).ConfigureAwait(false);
            }
            catch (global::System.Exception ______ex)
            {
                throw;
            }
```

See also https://learn.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#capture-and-rethrow-exceptions-properly for best practices regarding exception rethrowing

### Step to reproduce

1. Use refit in ASP .NET integration test
2. Force exception to be throw on the server
3. Notice the lack of stacktrace information

### Reproduction repository

https://github.com/Barsonax/CleanAspCoreWebApiTemplate/blob/main/CleanAspCore.Api.Tests/Endpoints/Departments/AddDepartmentsTests.cs

### Expected behavior

The full stack trace should be available

### Screenshots 🖼️

_No response_

### IDE

Rider Windows

### Operating system

Windows

### Version

_No response_

### Device

_No response_

### Refit Version

7.1.2

### Additional information ℹ️

_No response_

### PR DESCRIPTION
**Pull request by mithileshz**
**What kind of change does this PR introduce?**
Bug fix

**What is the current behavior?**
Fixes #1809
Currently there is a try/catch block surrounding the api call which rethrows the exception causing the stack trace to be discarded. 

**What is the new behavior?**
As the try catch block was not doing anything specific, it seemed better to remove it completely and have the original exception be thrown.

**What might this PR break?**
Not sure - different type of exceptions?

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Review by ChrisPulman — DISMISSED** [review]

**Comment by mithileshz** [comment]
Hmm looks like the unit test fails because the new stack trace is:
```
   at Refit.RequestBuilderImplementation.<>c__DisplayClass15_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in refit\Refit\RequestBuilderImplementation.cs:line 311
--- End of stack trace from previous location ---
   at Refit.Implementation.Generated.RefitTestsIGitHubApi.global::Refit.Tests.IGitHubApi.GetUser(String userName) in refit\Refit.Tests\obj\Debug\net6.0\InterfaceStubGeneratorV1\Refit.Generator.InterfaceStubGenerator\IGitHubApi.g.cs:line 174
   at Refit.Tests.RestServiceIntegrationTests.<>c__DisplayClass56_0.<<MissingBaseUrlThrowsArgumentException>b__0>d.MoveNext() in refit\Refit.Tests\RestService.cs:line 1704
--- End of stack trace from previous location ---
   at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in /_/src/xunit.assert/Asserts/Record.cs:line 105
```

This is because the method `AssertFirstLineContains` checks only the first line.

**Comment by ChrisPulman** [comment]
@mithileshz you should be able to run the test's on your machine to ensure all pass, thank you, let me know if you need any assistance.

**Comment by mithileshz** [comment]
@ChrisPulman Sorry, I thought I had run them all. I have done so now and pushed a new commit with the change. It's ready to review again :)

**Review by ChrisPulman — APPROVED** [review]

**Comment by ChrisPulman** [comment]
> @ChrisPulman Sorry, I thought I had run them all. I have done so now and pushed a new commit with the change. It's ready to review again :)

Thank you, you can relax now 😊

**Pull request merged**
