### PR TITLE
Add MemberNotNullWhen annotation for Content / HasContent pair

### PR DESCRIPTION
**Pull request by hansmbakker**
**What kind of change does this PR introduce?**

It adds the MemberNotNullWhen annotation to the Content / HasContent pair in ApiException.

**What is the current behavior?**

VS does not recognize `Content` being non-null when `HasContent` is `true`.

**What is the new behavior?**

VS should recognize `Content` being non-null when `HasContent` is `true`.

**What might this PR break?**

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by hansmbakker** [comment]
This is a continuation of https://github.com/reactiveui/refit/issues/1302

**Review by ChrisPulman — APPROVED** [review]

**Comment by hansmbakker** [comment]
@ChrisPulman I don't see how the error in the tests is linked to my change - can you please advise what to do?

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.71] Skipping: Refit.Tests (could not load dependent assembly 'Refit, Version=7.1.0'): Could not load file or assembly 'Refit, Version=7.1.0.0, Culture=neutral, PublicKeyToken=2f9b1262776509f5' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

**Comment by ChrisPulman** [comment]
> > @ChrisPulman I don't see how the error in the tests is linked to my change - can you please advise what to do?
> > ```
> > Starting test execution, please wait...
> > A total of 1 test files matched the specified pattern.
> > [xUnit.net 00:00:01.71] Skipping: Refit.Tests (could not load dependent assembly 'Refit, Version=7.1.0'): Could not load file or assembly 'Refit, Version=7.1.0.0, Culture=neutral, PublicKeyToken=2f9b1262776509f5' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
> > ```
> 
> I will take a look later, thank you.

You had not run the tests, this would have led to a failure of the API test due to a change in the API. I added these tests in to ensure that the version is correctly managed. 
I got heavily criticised for making a breaking change without bumping the version, now I can easily check if any of the API files have changed between the last release and this release and depending upon the changes made set the correct version. Hopefully this helps you to understand both why it was failing and the reason for me adding the API tests.

**Comment by hansmbakker** [comment]
I understand, thank you for helping me!

It was just that the build output didn't look like a test failure to me but more like a compilation failure (it couldn't find the DLL).

**Pull request merged**
