### PR TITLE
Change folder path to avoid implicit NuGet inclusions

### PR DESCRIPTION
**Pull request by sharwell**
@Mike-E-angelo I'm hoping we can use something like this PR to avoid needing to move these files completely outside the `analyzers` folder.

Fixes https://github.com/reactiveui/refit/pull/1216#issuecomment-902132236

### CODE REVIEW

**Comment by Mike-E-angelo** [comment]
Yeah it appears that any reference to this:

```
	<ItemGroup>
        <Analyzer Include="$(MSBuildThisFileDirectory)../../analyzers/cs-roslyn40/*.dll" />
    </ItemGroup>
```

Generates exceptions at build time.  I am curious on why removing it still loads it into `ServiceHub.RoslynAnalysisService.exe`.  If NuGet is auto-loading this into `ServiceHub.RoslynAnalysisService.exe` shouldn't we remove this `ItemGroup` altogether?

**Comment by sharwell** [comment]
OK this is going to be more annoying than I expected. I have to move these assemblies completely outside the analyzers folder. I'll update this PR.

https://github.com/dotnet/NuGet.BuildTasks/blob/b2f0c162994237c4a9c23af79d95f79847499ebd/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs#L468-L477

**Review by jmarolf — APPROVED** [review]

**Comment by clairernovotny** [comment]
Should this be merged?

**Comment by clairernovotny** [comment]
I'm going to go with yes :) I was confused by the close/reopen.

**Comment by sharwell** [comment]
> I was confused by the close/reopen.

Build had issues the first time; close/reopen triggered a new one.

**Comment by Mike-E-angelo** [comment]
Woohoo... I can confirm that this works like a champ now with preview5.  Thank you so much for doing this!  It really means a lot to me personally as there are a lot of fires burning in my world and this makes one less of them. :)  I appreciate the dedication to ensuring high quality of your work out there. 👍🙏

**Comment by clairernovotny** [comment]
@sharwell should I release this as stable?

**Comment by sharwell** [comment]
@clairernovotny the specific risk is as follows:

* If a consumer uses this package outside of NuGet tooling, or in a manner that doesn't add a source generator assembly from the customized location, `InterfaceStubGenerator` will not execute. If the build is likely to still succeed in this scenario (i.e. no compiler errors due to missing generated code), it's possible this user would experience a silent breaking change.
* For a while, the incremental source generator APIs were considered experimental and were only enabled if a consumer manually enabled `<LangVersion>preview</LangVersion>` in their project. If this behavior has not changed, it's possible for a user to experience a silent break inside the IDE for Visual Studio 2022.

All other potentially problematic cases should consistently use the old implementation (Roslyn 3.8 APIs) during builds, so even if there are bugs in the Roslyn 4.0 portion it should not manifest in the build outputs. Once confidence is built in the Roslyn 4.0 implementation, we can

**Comment by sharwell** [comment]
https://github.com/dotnet/roslyn/blob/c083dae9fcb112d82c18b89687b9af65e7ef77b7/src/Compilers/CSharp/Portable/SourceGeneration/CSharpGeneratorDriver.cs#L27

**Pull request merged**
