### PR TITLE
chore: rename tests add derived interface test

### PR DESCRIPTION
**Pull request by TimothyMakkison**
- Renamed `DerivedRefitInterfaceTest` and `DerivedNonRefitInterfaceTest`
- Added `InterfaceDerivedFromRefitBaseTest`

### CODE REVIEW

**Comment by TimothyMakkison** [comment]
@ChrisPulman did you have any thoughts regarding my [comment?](https://github.com/reactiveui/refit/issues/1791#issuecomment-2322902743) The lack of incremental generator tests are the main blocker preventing me from adding incremental generation.

**Comment by ChrisPulman** [comment]
> @ChrisPulman did you have any thoughts regarding my [comment?](https://github.com/reactiveui/refit/issues/1791#issuecomment-2322902743) The lack of incremental generator tests are the main blocker preventing me from adding incremental generation.

Could we go with Add a new **InterfaceStubGenerator.Roslyn41** option for the time being, this way we can maintain older versions as they currently exist and open a path to pure incremental generators, we can drop the relevant support if required once we get a stable version of 41.

**Review by ChrisPulman — APPROVED** [review]

**Comment by ChrisPulman** [comment]
Roslyn 38, 40 and 41 are all supported by Rider, VS2019 (Fully updated) and VS2022, so really using Roslyn 41 shouldn't be an issue.

**Comment by ChrisPulman** [comment]
I am happy with updating the version of Rosyln to a single newer version rather than trying to support 2 or 3 versions, this would involve changing the project setup to have a single NetStandard project instead of a shared project. 
Would you be okay with going down that route? 
While understanding that we will drop support for some versions of Visual Studio we can advance Refit to be what people are calling for. So, while keeping a version as low as possible i.e. Roslyn 41, I am happy with anything up to Roslyn 46 if that makes anything easier.

**Comment by TimothyMakkison** [comment]
> Would you be okay with going down that route?

I'm happy with either solution. My current solution was to update Roslyn 4.0 to Roslyn 4.1, this way we keep support for 3.9.

> we will drop support for some versions of Visual Studio we can advance Refit to be what people are calling for.
 
Personally, none of my planned changes require dropping support for anything. I only need 4.1 to use [`WithTrackingName`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.incrementalvalueproviderextensions.withtrackingname?view=roslyn-dotnet-4.7.0) to determine if the generator is caching correctly. This would be an extremely minimal change regardless of which approach is taken.

**Pull request merged**
