### PR TITLE
Added refit setting to bypass url verification

### PR DESCRIPTION
**Pull request by mjfara**
**Feature**
Added a new Refit Setting to allow bypassing of Url verification, specifically for use in a generic class for the Microsoft Dynamics Web API which uses OData.

**What is the current behavior?**
The current behavior enforces the url verification:

`VerifyUrlPathIsSane(RelativePath);`

```
static void VerifyUrlPathIsSane(string relativePath)
        {
            if (relativePath == "")
                return;

            if (!relativePath.StartsWith("/"))
                throw new ArgumentException($"URL path {relativePath} must start with '/' and be of the form '/foo/bar/baz'");
        }
```

**What is the new behavior?**
The new behavior adds an option to bypass this check:

```
if(refitSettings?.BypassUrlVerification != true)
                VerifyUrlPathIsSane(RelativePath);
```

**What might this PR break?**
This PR should have no effect on anything else, as the default behavior without changing this option is the same.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1113) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1113) before we can accept your contribution.<br/><br/>:x: mjfara [sign now](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1113)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/reactiveui/refit?pullRequest=1113) it.</sub>

**Comment by mjfara** [comment]
#988

**Comment by mjfara** [comment]
#1105

**Comment by clairernovotny** [comment]
As mentioned in https://github.com/reactiveui/refit/issues/1105#issuecomment-808791821, we won't be taking this change at this time. A custom delegating HttpHandler can alter the URL's as needed.

**Pull request closed without merging**
