### PR TITLE
Add MethodInfo property

### PR DESCRIPTION
**Pull request by donnytian**
**What kind of change does this PR introduce?**
feature

**What is the current behavior?**
As #1150 and #1156 described, currently, we are not able to get information on the executing method. The information is useful for url tags, additional behavior based on custom attributes, and other things.

**What is the new behavior?**
Added `MethodInfo` of the current method into request properties.
Now you can grab the custom attributes and other method info from the request properties in `DelegatingHandler`.
```cs
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        // Get the methodInfo of the current method
        var methodInfo = (MethodInfo)request.Properties[HttpMessageRequestOptions.MethodInfo];

        // do something with methodInfo with method name, custom attributes and etc.

        return await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
    }
```

**What might this PR break?**
There is nothing to break. Just one additional item in the request property/option list.

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:
NA

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1219) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1219) before we can accept your contribution.<br/><br/>:x: donnytian [sign now](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1219)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/reactiveui/refit?pullRequest=1219) it.</sub>

**Comment by RyuzakiH** [comment]
Can someone review this? It's not that big, but it makes things easier.

**Comment by netssfy** [comment]
I think strong type is reasonable, because refit http attributes are applied on the method which is a strong type.
So I also want to know why @anaisbetts choose storing a string with method name?

**Comment by james-s-tayler** [comment]
Seems this is an issue people seem to have a difference of opinion hence why I liked my configurable approach... :(

**Comment by donnytian** [comment]
> Seems this is an issue people seem to have a difference of opinion hence why I liked my configurable approach... :(

I love it too. I love either of them to be merged more. Our project currently is using an ugly&complex workaround to just get the executing method...

**Comment by donnytian** [comment]
> Seems this is an issue people seem to have a difference of opinion hence why I liked my configurable approach... :(

I love it too. I love either of them to be merged more. Our project currently is using an ugly&complex workaround to just get the executing method...

**Comment by 0xced** [comment]
I just opened #1317 which is very closely related but goes a little bit further by exposing the full `RestMethodInfo` and also provides new `HttpRequestMessageOptions.InterfaceTypeKey` and `HttpRequestMessageOptions.RestMethodInfoKey` properties to ease retrieving the request options.

But I should definitively have looked at open pull requests first!

**Comment by 0xced** [comment]
> Seems this is an issue people seem to have a difference of opinion hence why I liked **my configurable approach**... :(

If I understand correctly, you are talking about #1180, am I right?

**Comment by gabrielmaldi** [comment]
I would love to have this to be able to override `HttpClient`'s timeout on a per-operation basis:

```csharp
services
    .AddRefitClient()
    .ConfigureHttpClient(httpClient => httpClient.Timeout = TimeSpan.FromSeconds(30));
```

```csharp
public class HttpMessageHandler : DelegatingHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var timeoutSeconds = 15; // ToDo: read configuration for operation identified by request.Options[HttpRequestMessageOptions.MethodInfo]
        using var timeoutTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(timeoutSeconds));
        return await base.SendAsync(request, timeoutTokenSource.Token);
    }
}
```

**Pull request closed without merging**
