### PR TITLE
chore: run csharpier

### PR DESCRIPTION
**Pull request by TimothyMakkison**
Ran csharpier `0.25.0`, haven't made any other changes.

See #1596 & #1602

### CODE REVIEW

**Comment by anaisbetts** [comment]
I think we probably also want to set this up as a build tool? Running it Just Once doesn't really make much sense

**Comment by TimothyMakkison** [comment]
Good idea, I'm not the best at CI but I know how to run csharpier via husky if that's okay

**Comment by anaisbetts** [comment]
Paging @ChrisPulman @glennawatson who I bet have a great idea on how to do this

**Comment by glennawatson** [comment]
We can enforce the stylecop rules which probably be more useful long term. What we do on other rxui projects. Basically means it won't get out of control again. 

Stylecop has the advantage of allowed exception etc.

**Comment by TimothyMakkison** [comment]
#1622 should automatically run csharpier on all commits.

**Comment by glennawatson** [comment]
I'd prefer we don't run the csharpier ever commit and we use stylecop analysers to maintain the styling. It has more flexibility then overriding deliberate style choices.

**Comment by TimothyMakkison** [comment]
Fair enough, as long as the solution removes the whitespace I'm happy 😊

**Comment by glennawatson** [comment]
Let's commit this one as a one time commit, I just don't want this running EVERY commit.

Sorry for the confusion.

**Comment by glennawatson** [comment]
Apologies, can you rerun the application on that failing file? Thanks.

**Review by glennawatson — APPROVED** [review]

**Pull request merged**
