### PR TITLE
Added: Support for Nullable References

### PR DESCRIPTION
**Pull request by joelweiss**
**What kind of change does this PR introduce?**
Support for Nullable References

**What is the current behavior?**
#738 

**What is the new behavior?**
Figure out if the nullable is a reference type, if yes 
- Don't include the `?` in the `typeof(string?)`
- Emit `#nullable enable annotations` and `#nullable disable annotations` around the generated stubs where Nullable References are used. 

**What might this PR break?**
Nothing that I can think of.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
Before it didn't compile, now it does. Do we need any other tests?
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

There are still 2 issues with this PR, I just wanted to start a discussion to see if this is the direction you want to go
1. It doesn't detect if the return type is a Generic Nullable Reference and doesn't emit the `#nullable enable annotations`, I asked on [StackOverflow](https://stackoverflow.com/questions/59097649/how-do-i-check-with-roslyn-if-a-type-is-a-nullable-reference) why this is
2. It currently only supports  Nullable References where the Type is declared in mscorlib, if we want to support it, we will have to figure out all the reference of the dll containing the Refit interfaces.

Not supported:
```csharp
interface ICustomNullableReferenceResultAndParameterService
{
    [Get("/")]
    Task<CustomReference> Get(CustomReference? reference);
}

internal class CustomReference
{
    public int MyProperty { get; set; }
}
```

### CODE REVIEW

**Comment by ilya-spv** [comment]
Not sure if you got that covered, but a little note: it can be an indirect reference type, e.g.:

`IDictionary<string, object?>`

This one does not break compilation, but generates a warning, so some annotations might be required I suppose.

I am also wondering if we can just put `#nullable enable annotations` on the whole generated code or it would break too much?

**Comment by Dreamescaper** [comment]
What do you think about creating some helper method (e.g. `ToNullable`) for Type, and use it to handle nullability in runtime (do nothing for reference types, create nullable type for value types)?
That would allow to handle types outside of mscorlib.

**Comment by joelweiss** [comment]
Rebased, and no longer emitting the `#nullable enable` (we can not always due to older compilers and detecting if nullable reference types were used didn't pan out)
I went with @iron9light's [recommendation](https://github.com/reactiveui/refit/issues/738#issuecomment-602167576) and just disabled the nullable warnings.

This PR still only recognizes a _nullable reference type_ from mscorelib, @Dreamescaper I don't understand what you are suggesting, can you please elaborate?

**Comment by Dreamescaper** [comment]
@joelweiss 
So every time `typeof` for nullable type is used (both value type or reference type), I suggest using something like that:
```
		ToNullable(typeof(MyType))

		...

        private static Type ToNullable(Type type)
        {
            if (!type.IsValueType)
                return type;

            return typeof(Nullable<>).MakeGenericType(@this);
        }
```

This way you don't need any semantic info in compile time.

**Comment by joelweiss** [comment]
@Dreamescaper 
Oh nice, I will try it out.

**Comment by clairernovotny** [comment]
How about only adding that method if it's needed?

**Comment by joelweiss** [comment]
@clairernovotny 
Ok I will do that

**Comment by joelweiss** [comment]
@Dreamescaper your suggestion worked very well.
@clairernovotny I changed to emit the `ToNullable()` only when necessary.

Anything else? otherwise this PR is ready for review.

**Comment by joelweiss** [comment]
Thanks @iron9light and @Dreamescaper, your suggestion were incorporated in this PR.

I think we can close Issue #738

**Pull request merged**
