### PR TITLE
Fixes #627, #637 and relates to #573

### LINKED ISSUE #627: AuthorizationHeaderValueGetter should be Func<HttpRequestMessage, Task<string>>
Generating the OAuth signature requires access to the HttpRequestMessage, not currently granted.

### PR DESCRIPTION
**Pull request by benjaminhowarth1**
Updates the signature for AuthorizedHeaderValueGetter to support passing a HttpRequestMessage to the function

### CODE REVIEW

**Comment by onovotny** [comment]
The way this is structured, it would be a breaking change. Is there a way you can restructure it so it's additive?

**Comment by benjaminhowarth1** [comment]
Stand by 🙂

**Comment by benjaminhowarth1** [comment]
PR updated with additive class, ready to merge.

**Comment by onovotny** [comment]
The code and tests look good. Can you please update the docs with the appropriate changes to reflect the new functionality and then I can merge?

**Comment by benjaminhowarth1** [comment]
Done!

**Comment by onovotny** [comment]
Can you doc the auth updates too? There are a few things in this PR.

**Comment by benjaminhowarth1** [comment]
Completed.

**Pull request merged**
