### PR TITLE
feat: custom query key formatters

### PR DESCRIPTION
**Pull request by tcortega**
**What kind of change does this PR introduce?**

Feature and docs update.

**What is the current behavior?**

Query keys in the URL are formatted based on property names without any customization. 

**What is the new behavior?**

Introduces the capability for users to define custom formatting strategies for query keys in the URL. This can be achieved by implementing the `IUrlParameterKeyFormatter` interface and setting it in `RefitSettings`. The default behavior remains unchanged (using property names as they are) to ensure backward compatibility. Also, the documentation has been updated to reflect these changes and guide users on how to utilize this feature.

**What might this PR break?**
Care has been taken to ensure retro-compatibility. This PR should not introduce any breaking changes, as the default behavior remains consistent with previous versions.

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:
- The `AliasAs` attribute always takes precedence in key naming, regardless of any custom key formatters in use.
- Enhanced documentation has been added to clarify the behavior of `IUrlParameterFormatter` when dealing with dictionaries.
- The current handling of dictionary formatting remains unchanged to ensure backward compatibility and prevent potential breaks for existing users.
- The decision to prioritize the `AliasAs` attribute aligns with intuitive expectations and mirrors behaviors such as `JsonPropertyName` in System.Text.Json.
- Formatters are designed to be straightforward: they accept a string and return a formatted version without considering other attributes or extraneous factors.

### CODE REVIEW

**Comment by tcortega** [comment]
Closes #1333
Closes #1541
Closes #1258

There are probably more issues regarding this matter.

**Comment by Thepriestdude** [comment]
Can this be looked into, or is the PR stale?

**Comment by tcortega** [comment]
> Can this be looked into, or is the PR stale?

I guess they're too busy

**Comment by ChrisPulman** [comment]
I was looking at this at the weekend, but I was away in Scotland, I working my way through the PR's to get them all dealt with appropriately. I will try to find time this weekend to go through this

**Comment by ChrisPulman** [comment]
@tcortega Please could you recheck the code you have added after the merge to be sure it still covers the same intended update

**Comment by tcortega** [comment]
> @tcortega Please could you recheck the code you have added after the merge to be sure it still covers the same intended update

I'll check it either later tonight or tomorrow

**Comment by tcortega** [comment]
@ChrisPulman From my end, based on my changes, this is pretty much what I can do testing-wise.

**Comment by TimothyMakkison** [comment]
It looks like your unintentionally reverted #1619 when merging to the main branch, do you want me to fix this?

**Comment by ChrisPulman** [comment]
@TimothyMakkison yes please

**Comment by ChrisPulman** [comment]
@TimothyMakkison Trying to check everything as best as possible after the merges and updates to ensure all is still intact ready for a release, thank you for spotting this.

**Pull request merged**
