### PR TITLE
Trim trailing / from hostUrl #610

### PR DESCRIPTION
**Pull request by tstivers1990**
Solves #610 

I attempted to add a unit test for this, but I was unable to find a good way to go about testing it. There doesn't seem to be a way to inject an `HttpClient` while also passing the `hostUrl` and, naturally, there is no way to access the `HttpClient` that is created from the result. At least not that I'm aware of.

If you know how to go about unit testing this change, I'd be glad to implement the unit test as well.

### CODE REVIEW

**Comment by onovotny** [comment]
You can add a property called Client of type HttpClient on an interface and it’ll return the concrete instance. 

I’d also suggest adding a NullOrEmpty check against the url parameter.

**Comment by tstivers1990** [comment]
> You can add a property called Client of type HttpClient on an interface and it’ll return the concrete instance.

Ah. I'll add the unit test shortly, then.

> I’d also suggest adding a NullOrEmpty check against the url parameter.

Yes I definitely should have used the null coalescing operator before `.TrimEnd()`. Good catch. As far as checking IsNullOrEmpty, I'm willing to do that but I think it would be more appropriate to put that in it's own issue/pull request as it's a bug in it's own right. What is the expected behavior if "baseUrl" is null or empty? Throw `InvalidArgumentException`? If this is the case, there wouldn't be a need for the null coalescing operator.

**Comment by onovotny** [comment]
Yeah, I think invalid argument exception would work.

**Comment by tstivers1990** [comment]
@onovotny I'm not sure why that test failed after I added the unit test. Are you? Doesn't appear I changed anything that would have caused it to fail. Can you also confirm whether or not my last commit should have been committed, or if those files should be left out of git.

**Pull request closed without merging**
